aliyun:
  ons:
    accessKeyId: t5zToaOwDy3Vmzon
    accessKeySecret: rX1SHIQMQOIXH2NuwMRKAwrOOgQRJn
  rocketmq:
    ipAddress: 127.0.0.1:9876
    producerGroupName: ProducerGroupName
    consumerGroupName: ConsumerGroupName


logging:
  level: info
spring:
  profiles:
    active: DEV