aliyun:
  ons:
    accessKeyId: t5zToaOwDy3Vmzon
    accessKeySecret: rX1SHIQMQOIXH2NuwMRKAwrOOgQRJn
  rocketmq:
    ipAddress: 192.168.230.128:9876
    producerName: Producer

logging:
  level: info
spring:
  profiles:
    active: TEST